---
- name: AVIDIAN - CONFIGURE CSR1000V PART 1
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:

    - name: CONFIGURE IP ADDRESS
      ios_config:
        parents: "interface GigabitEthernet1"
        lines:
          - ip address 192.168.56.101 255.255.255.0
          - no shutdown

    - name: CONFIGURE USER ACCOUNT
      ios_config:
        lines:
          - username admin privilege 15 secret admin123!

    - name: CONFIGURE BANNER MESSAGE
      ios_config:
        lines:
          - banner motd @ UNAUTHORIZED ACCESS PROHIBITED - ROTI KANAI @
