---
# MASTER PLAYBOOK - ROTI KANAI AUTOMATION SOLUTION

- import_playbook: avidian_router_part1.yml
- import_playbook: danial_router_part2.yml
- import_playbook: mervyn_linux_part1.yml
- import_playbook: tee_linux_part2.yml
